-- 自动生成，请勿手改：node scripts/import-career-roadmap.mjs
-- 数据源：.\docs\seeds\career-roadmap-data.json
-- 生成时间：2026-08-02T14:31:42.553Z
-- 幂等：全部 INSERT OR REPLACE + 确定性主键，可重复执行。
-- 顺序：父表先于子表（REPLACE 会触发 ON DELETE CASCADE），不要重排语句。

-- 分片 3/4

INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (201, 2, 1, '打基础：搞懂业务和账', '0-2 个月', '建立完整的企业经营流程认知，能把一笔生意从接单到收款在系统里的每一步讲清楚', '对着一张销售订单，完整口述它在 ERP 里触发的全部单据、库存变动和会计分录，不看资料', '["销售订单到出货收款完整走一遍，涉及哪些模块和单据","MRP 的输入输出是什么，为什么它依赖 BOM 和库存准确性","采购三方匹配是什么，它防的是什么风险","标准成本和实际成本的差异从哪来"]', '["一份完整的订单到收款业务流程图，标注每一步的单据与系统模块","一份 ERP 八大模块职责与数据流向对照笔记"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (202, 2, 2, '上手：能配置能跑通', '2-6 个月', '能在测试环境里独立完成一个模块的完整配置，并带客户关键用户跑通业务闭环', '独立配置一个模块并通过关键用户测试，客户能按配置完成日常业务而不需要顾问在旁', '["物料主数据哪些参数会直接影响 MRP 结果，配错会怎样","库存账实不符你怎么查","月结卡住不能过账，可能有哪些原因","客户要求的功能标准系统没有，你怎么处理"]', '["一个模块的完整配置文档与参数说明","一套关键用户测试用例与测试结果记录","一份主数据整理模板与校验规则清单"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (203, 2, 3, '独立：主导蓝图和上线', '6-18 个月', '能独立负责蓝图设计与上线切换，对项目范围、进度和客户接受度负责', '主持完成一次业务蓝图评审并获客户签字，随后主导数据迁移与上线切换，首次月结顺利关账', '["业务蓝图包含哪些内容，你怎么保证客户签字后不反悔","Fit-Gap 里你判断一个需求不该做的依据是什么","数据迁移你怎么设计校验和回退","上线后账不平，你的排查顺序是什么"]', '["一份通过客户评审的业务蓝图文档","一份带成本估算的 Fit-Gap 差异分析清单","一份数据迁移方案与期初对账报告"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (204, 2, 4, '资深：管项目和做整体方案', '1.5-3 年', '能管理完整项目的范围、进度、成本与客户关系，并输出跨系统的企业级数字化方案', '作为项目负责人交付一个百万级项目，控制在预算与工期内验收，客户愿意签二期', '["项目范围失控的信号有哪些，你怎么控","客户高层和业务部门意见冲突，你站哪边","讲一个你做过的 ERP 与其他系统的集成方案","项目延期已成定局，你怎么和客户谈"]', '["一份企业级数字化整体规划方案","一套项目管理模板（计划、风险、变更、验收）","一份跨系统集成架构设计文档"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (301, 3, 1, '打基础：懂业务也懂库', '0-2 个月', '能读懂 MES 的数据库结构和业务含义，知道每张核心表存什么、和哪些业务动作对应', '拿到一套 MES 的库表结构，能自己画出工单、物料、报工、质检四条主线的表关系图并说明业务含义', '["MES 里工单、工序、报工三者的数据关系怎么设计","一条报工记录应该包含哪些字段，为什么","INNER JOIN 和 LEFT JOIN 的结果差异在业务上意味着什么","怎么在 Linux 上查看一个服务的实时日志"]', '["一份 MES 核心表关系图与字段业务含义说明","一份常用查询练习集，覆盖工单、报工、库存三类场景"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (302, 3, 2, '上手：能接需求能交付', '2-6 个月', '能独立完成中小型定制需求的开发与自测，交付的功能不因明显逻辑错误被打回', '独立交付三个定制报表和一个数据接口，上线后一个月内无重大缺陷', '["一张报表数据翻倍了，可能是什么原因","怎么设计一个接口保证重复调用不会产生重复数据","生产环境要改一批数据，你的操作步骤是什么","客户提的需求你觉得不合理，你怎么沟通"]', '["三个定制报表的取数逻辑说明与 SQL","一个数据接口的接口文档与测试用例","一份带事务与回退的数据修正脚本模板"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (303, 3, 3, '独立：能设计能优化', '6-18 个月', '能独立设计一个定制模块的技术方案，并对系统性能与线上稳定性负责', '独立设计并交付一个跨系统集成模块，同时完成一次慢查询治理，把核心看板响应时间降到秒级', '["一条查询从 10 秒优化到 1 秒，你的排查和优化路径是什么","复合索引的最左前缀是什么意思，什么情况下索引会失效","接口调用失败怎么设计重试和补偿，怎么保证不重复","定时任务没执行，你怎么排查"]', '["一份集成模块的技术设计文档，含数据流、异常处理与对账机制","一份性能优化报告，含优化前后的执行计划与耗时对比","一套数据质量校验脚本与巡检机制"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (304, 3, 4, '资深：定架构和技术标准', '1.5-3 年', '能为多项目复用制定技术架构与开发规范，主导复杂集成与大规模数采场景的技术决策', '主导一次平台级技术改造或一个大规模数采项目落地，并建立团队开发规范被实际执行', '["系统上线两年后越来越慢，你怎么做整体治理","怎么设计一套能同时支撑十几个客户个性化需求的架构","讲一次你主导的技术选型，取舍依据是什么","怎么让团队的开发规范真正被执行而不是文档躺着"]', '["一份平台级技术架构设计与演进路线","一套团队开发规范与代码审查清单","一份大规模数采场景的容量评估与技术方案"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (401, 4, 1, '打基础：懂设备也懂网络', '0-2 个月', '能看懂点表和网络拓扑，知道一个设备信号从传感器到系统要经过哪几层', '对着一台陌生设备的电气图和点表，说出它有哪些可采集信号、每个信号代表什么状态、该用什么方式接入', '["PLC 的扫描周期是什么，它对数据采集有什么影响","数字量和模拟量的区别，各自典型采集什么","工业以太网和普通以太网有什么不同","设备状态用哪些信号组合来判断运行、停机、故障"]', '["一份设备信号清单与采集方式建议","一份车间网络拓扑草图，标注每段的介质与协议"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (402, 4, 2, '上手：能调通一台设备', '2-6 个月', '能独立完成单台或几台设备的数据采集配置，从物理连接到数据入库全程自己搞定', '独立把一台陌生设备的数据采集到系统里，数据与现场实际值一致，连续运行一周无异常断流', '["Modbus 寄存器地址和文档地址差 1 是怎么回事","OPC UA 相比传统 OPC 好在哪，订阅怎么配","设备数据每天定时断一次，你怎么查","怎么验证采上来的数据是准确的"]', '["一份设备接入的完整配置文档与连通测试记录","一份数据准确性比对报告","一份抓包分析记录，说明一次通讯问题的定位过程"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (403, 4, 3, '独立：能设计一条产线的数采', '6-18 个月', '能独立完成整条产线的数采方案设计与实施，包含协议选型、点表制定、握手设计和异常处理', '独立交付一条产线的完整数采，稼动率数据可直接用于生产例会，现场认可数据可信', '["一条产线设备品牌五花八门，你怎么统一接入","MES 要下发配方到设备，握手协议你怎么设计才不会卡死","网络断了两小时，这期间的数据怎么办","客户说稼动率算得不对，你怎么排查"]', '["一份产线数采方案，含协议选型依据与网络拓扑","一份完整点表与地址规划文档","一份 MES 与设备的握手协议设计说明"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (404, 4, 4, '资深：做全厂数采架构', '1.5-3 年', '能为全厂或多厂区设计数采与 OT 网络架构，对数据完整性、链路可靠性和长期可运维性负责', '主导一个全厂级设备联网项目落地，设备接入率与数据完整率达标并稳定运行半年以上', '["新建工厂让你规划 OT 网络，你怎么分段、怎么做冗余","IT 部门要求打补丁，生产不同意停机，你怎么协调","上千个采集点，怎么评估网络和服务器扛不扛得住","多厂区数据要汇总到集团，你的架构怎么设计"]', '["一份全厂 OT 网络与数采架构设计文档","一份 IT/OT 隔离与安全方案","一份数采容量评估报告与边缘节点运维方案"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (501, 5, 1, '打基础：先看懂自家工厂', '0-2 个月', '能完整讲清本企业从接单到出货的业务流程，以及现有系统各自管了哪一段', '独立画出本企业的业务流程与系统现状图，标出信息断点和仍在用手工表格的环节', '["介绍你们公司的生产流程和现有系统","ERP 和 MES 分别解决什么问题，边界在哪","你们目前哪些环节还在用手工表格，问题是什么","怎么判断一个业务部门提的需求是真需求"]', '["一份本企业业务流程与系统现状图","一份手工作业环节清单与痛点记录"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (502, 5, 2, '上手：能提需求能验收', '2-6 个月', '能独立编写业务需求说明并参与厂商方案评审，能对交付内容做实质性验收而不是走过场', '独立主导一个模块的需求提出、方案评审和验收，验收时能指出方案中的实际问题', '["厂商说这个需求要二开加钱，你怎么判断合不合理","验收时你会重点检查什么","主数据整理为什么是甲方的责任而不是厂商的","产品编码规则你会怎么设计"]', '["一份业务需求说明书","一份供应商方案对比评估表","一套验收测试用例与数据核对脚本"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (503, 5, 3, '独立：能管一个项目', '6-18 个月', '能作为甲方项目负责人管理一个系统项目，控制范围与进度并推动内部业务部门真正配合', '作为甲方负责人推动一个系统按期上线，业务部门实际使用率达标而非上线即闲置', '["业务部门不配合数据整理，你怎么推","项目延期了，你作为甲方怎么处理与厂商的关系","系统上线后没人用，可能是什么原因","怎么评估一个项目的实际收益"]', '["一份项目管理计划与风险清单","一份上线切换与培训推广方案","一份上线后的数据核对与使用率分析报告"]');
INSERT OR REPLACE INTO career_stages (id, career_id, stage, title, duration, goal, milestone, interview_points, deliverables) VALUES (504, 5, 4, '资深：做企业数字化规划', '1.5-3 年', '能站在企业整体视角规划系统蓝图与投入节奏，对多系统的协同、数据资产和长期成本负责', '输出并通过管理层评审的三年数字化规划，且首年落地项目按规划完成', '["让你做公司三年数字化规划，你从哪几个维度切入","已有的几个系统数据打不通，你怎么治理","怎么向管理层论证一笔数字化投入的回报","自建团队还是全部外包，你怎么权衡"]', '["一份企业三年数字化规划与年度预算建议","一份跨系统数据治理与主数据管理方案","一份供应商管理与长期运维策略"]');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 11, 55, 0 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 55 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 11, 56, 1 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 56 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 11, 57, 2 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 57 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 11, 58, 3 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 58 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 11, 59, 4 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 59 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 11, 60, 5 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 60 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 11, 61, 6 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 61 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 11, 62, 7 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 62 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 11, 63, 8 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 63 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 21, 64, 0 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 64 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 21, 65, 1 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 65 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 21, 66, 2 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 66 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 21, 67, 3 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 67 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 21, 68, 4 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 68 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 21, 69, 5 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 69 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 21, 70, 6 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 70 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 21, 71, 7 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 71 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 305, 0 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 305 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 306, 1 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 306 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 307, 2 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 307 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 308, 3 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 308 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 309, 4 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 309 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 310, 5 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 310 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 311, 6 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 311 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 312, 7 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 312 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 313, 8 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 313 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 314, 9 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 314 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 315, 10 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 315 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 316, 11 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 316 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 317, 12 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 317 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 318, 13 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 318 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 319, 14 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 319 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 320, 15 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 320 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 1, 16 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 1 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 2, 17 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 2 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 3, 18 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 3 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 4, 19 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 4 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 5, 20 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 5 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 22, 6, 21 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 6 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 31, 72, 0 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 72 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 31, 73, 1 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 73 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 31, 74, 2 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 74 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 31, 75, 3 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 75 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 41, 76, 0 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 76 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 41, 77, 1 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 77 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 42, 78, 0 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 78 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 42, 79, 1 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 79 AND status = 'published');
INSERT OR REPLACE INTO track_level_chapters (level_id, chapter_id, sort) SELECT 53, 80, 0 WHERE EXISTS (SELECT 1 FROM chapters WHERE id = 80 AND status = 'published');
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (1, 101, 21, 'core', '七大模块的概念是这个岗位所有对话的基础词汇，不懂就没法参与需求讨论', 0);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (2, 101, 11, 'important', 'MES 的工单和物料几乎都来自 ERP，不知道上游怎么来的就会在集成时抓瞎', 1);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (3, 101, 31, 'important', '第一次被客户问「这个数字怎么来的」时，能自己查表比等开发回复快一天', 2);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (4, 101, 81, 'optional', '先能看懂现场标签和扫码动作，编码规则设计等到中级阶段再学', 3);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (5, 102, 22, 'core', '配置能力是这个阶段的立身之本，16 章核心知识加 6 章实操是必须啃完的部分', 0);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (6, 102, 32, 'core', '数据整理和导入校验全靠 SQL，导错一批主数据可能让整个测试环境重来', 1);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (7, 102, 81, 'important', '扫码作业是现场最高频的动作，配置时必须知道标签和扫码流程怎么设计', 2);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (8, 102, 12, 'important', '整理主数据时要和客户 ERP 的物料、BOM 对齐，不懂 ERP 参数会把脏数据带进来', 3);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (9, 102, 71, 'optional', '客户环境偶尔需要重启服务或看日志，会基础命令能少求人', 4);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (10, 103, 23, 'core', '需求边界界定、集成设计、上线切换这三件事决定项目成败，是独立带项目的分水岭', 0);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (11, 103, 33, 'important', '上线后数据量涨上来，看板变慢和数据对不上都要自己能定位', 1);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (12, 103, 12, 'important', '对接客户 ERP 时要能和对方顾问平等对话，讲清接口需求和数据口径', 2);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (13, 103, 61, 'important', '现场数据断了先怀疑网络，至少要能画出拓扑并做基本排查，不然只能干等', 3);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (14, 103, 72, 'important', '很多客户没有运维，部署、备份、日志排查都得实施工程师自己兜底', 4);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (15, 103, 91, 'important', '独立带项目后要自己开调研会、写纪要、拿需求确认单签字，缺了这层项目边界守不住，需求会无限追加', 5);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (16, 104, 23, 'core', '复杂项目的方案能力来自对生产形态和集成架构的深度理解，这一级要反复实践加深', 0);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (17, 104, 13, 'important', '做整体数字化方案时要能覆盖 ERP 侧的蓝图与集成，只懂 MES 接不了大单', 1);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (18, 104, 83, 'important', '集团级项目必然涉及统一编码体系和完整追溯链设计，这是方案里的硬骨头', 2);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (19, 104, 62, 'optional', '涉及设备联网的项目里能自己评估网络可行性，减少对第三方的依赖', 3);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (20, 104, 41, 'optional', '能看懂点表、和电气工程师对上话即可，深度调试交给 SCADA 数采岗位', 4);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (21, 104, 92, 'core', '同时管两个以上项目并对交付日期负责，实施计划编制、UAT 组织与上线切换必须能自己扛，这是升项目经理的硬门槛', 5);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (22, 201, 11, 'core', '八大模块的职责与单据流是这个岗位的全部对话基础，必须先建立完整认知框架', 0);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (23, 201, 31, 'important', '客户质疑报表数字时能自己查库验证，是顾问建立专业信任的第一道门槛', 1);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (24, 201, 21, 'optional', '了解车间那一层在干什么，避免把 ERP 的生产模块当成万能，为后续集成打底', 2);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (25, 202, 12, 'core', '主数据治理、MRP 参数、库存事务、成本核算、月结，这五块是顾问的日常战场', 0);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (26, 202, 32, 'important', '数据整理、导入校验、期初对账都要写查询，靠开发排队会拖垮项目进度', 1);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (27, 202, 21, 'important', '客户几乎都会问「以后上 MES 怎么办」，答不上来会显得方案不完整', 2);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (28, 203, 13, 'core', '蓝图设计、Fit-Gap、数据迁移、集成架构，这四项是独立顾问的核心交付能力', 0);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (29, 203, 32, 'core', '期初建账与迁移校验的数据量大且不容出错，必须能自己写脚本逐项对平', 1);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (30, 203, 22, 'important', '设计 ERP 与 MES 的边界与接口时，要能理解车间侧的数据粒度和报工逻辑', 2);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (31, 203, 92, 'important', '独立主导蓝图评审与上线切换，本质是组织工作而非配置工作，计划编制与 UAT 组织的能力决定项目能不能按期收口', 3);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (32, 204, 13, 'core', '项目管理能力必须建立在对 ERP 全模块的掌握上，否则控不住范围也压不住客户的临时需求', 0);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (33, 204, 23, 'important', '企业级方案通常是 ERP 加 MES 一体规划，只会 ERP 会被限制在单系统项目里', 1);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (34, 204, 33, 'important', '系统跑几年后的性能与数据治理问题会找上门，要能给出结构性方案', 2);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (35, 204, 71, 'optional', '客户自建机房部署时能参与讨论环境要求，不至于完全依赖厂商技术', 3);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (36, 204, 93, 'core', 'ERP 项目周期长达半年到一年，范围蔓延与变更管理是利润的生死线，这一级不达标就管不了百万级项目', 4);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (37, 301, 31, 'core', '这个岗位的日常输入输出大部分是 SQL，基础不牢后面每一步都要返工', 0);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (38, 301, 21, 'core', '不懂业务写出来的功能会是「客户说啥做啥」，改三轮还不对，业务认知是省时间的投资', 1);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (39, 301, 71, 'important', '开发环境和测试环境都在 Linux 上，连不上服务器查不了日志就无法自助排查', 2);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (40, 302, 32, 'core', '报表开发的本质就是取数，CTE、窗口函数和 NULL 陷阱是每天都会碰到的东西', 0);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (41, 302, 22, 'core', '配置能做到的事不该写代码，不懂标准功能边界会做大量无用的二开', 1);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (42, 302, 71, 'core', '自己部署自己排查是这个阶段的独立性要求，不能每次都找运维', 2);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (43, 302, 101, 'core', '接需求写代码是这个岗位的定义性动作，读懂已有代码并改对一处逻辑是进入交付状态的最低门槛', 3);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (44, 303, 33, 'core', '数据量上千万后，执行计划、索引设计和预聚合是解决性能问题的唯一手段', 0);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (45, 303, 72, 'core', '部署、定时任务、日志排查、备份恢复是二开人员必须自己扛的运维半径', 1);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (46, 303, 23, 'important', '做集成模块时必须理解接口的业务语义与对账要求，只按字段开发一定出问题', 2);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (47, 303, 61, 'important', '接口连不上时要能先判断是网络还是程序，避免把网络问题当成代码 bug 查半天', 3);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (48, 303, 102, 'core', '独立交付集成模块要求能自己搭工程、写接口、控事务、做自测，这一级是独立开发者的完整能力包', 4);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (49, 304, 33, 'core', '数据架构决策的深度直接决定系统能不能撑到三年后，是这个层级最硬的能力', 0);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (50, 304, 23, 'core', '架构决策必须建立在对业务演进的判断上，只看技术会做出用不了的设计', 1);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (51, 304, 73, 'important', '高可用、监控告警、容量规划是对交付系统长期负责的必要能力', 2);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (52, 304, 62, 'important', '大规模数采项目的瓶颈常常在链路而非代码，要能参与网络与容量的联合评估', 3);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (53, 304, 82, 'important', '扫码与追溯是二开需求的高发区，要懂防错校验和性能约束才能设计对', 4);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (54, 304, 103, 'core', '平台级架构、插件扩展点与多客户版本管理是技术负责人的核心职责，只会写功能带不了团队也撑不住产品演进', 5);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (55, 401, 41, 'core', '点表看不懂就无法与电气工程师协作，这是进入这个岗位的第一道门', 0);
INSERT OR REPLACE INTO career_stage_reqs (id, stage_id, level_id, importance, note, sort) VALUES (56, 401, 61, 'core', '数据传不上来八成是网络问题，连拓扑都画不出就只能靠猜', 1);
